package org.meow.autistic.data.task

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.Instant

/**
 * syncStatus values: "local" | "synced" | "pending_push" | "pending_delete"
 * extraPropertiesJson is a JSON blob embedded in the Google Tasks notes field alongside [notes].
 */
@Entity(tableName = "tasks")
data class TaskEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val task: String,
    val isCompleted: Boolean = false,
    val createdAt: Instant,
    val dueAt: Instant? = null,
    val notes: String? = null,
    val category: String = "General",
    val reminderSet: Boolean = false,
    val googleTaskId: String? = null,
    val googleTaskListId: String? = null,
    val extraPropertiesJson: String? = null,
    val lastSyncedAt: Instant? = null,
    val syncStatus: String = "local",
    /** Non-null when this task was generated by a [DailyTaskEntity]; holds its parent id. */
    val dailyTaskId: Long? = null,
    /** Expected duration in minutes. Null means no estimate. */
    val expectedTimeMinutes: Int? = null,
    /** Minutes before [dueAt] to fire a reminder. Null means no reminder scheduled. */
    val reminderMinutesBefore: Int? = null,
)
